// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmmAJbx9EI2bE7vfIhHY1q82hjA3MVkY',
    appId: '1:75887553218:web:09f31a4362c0289404695b',
    messagingSenderId: '75887553218',
    projectId: 'th1-firebase',
    authDomain: 'th1-firebase.firebaseapp.com',
    storageBucket: 'th1-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApKzBqYuy4lRQ6rvp_xlpp_GuhU9OAZL8',
    appId: '1:75887553218:android:6440de252583cb6204695b',
    messagingSenderId: '75887553218',
    projectId: 'th1-firebase',
    storageBucket: 'th1-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QWylVChxu0kwtlIslQL_jcODWfxyrIs',
    appId: '1:75887553218:ios:dcfcca69148c631504695b',
    messagingSenderId: '75887553218',
    projectId: 'th1-firebase',
    storageBucket: 'th1-firebase.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8QWylVChxu0kwtlIslQL_jcODWfxyrIs',
    appId: '1:75887553218:ios:dcfcca69148c631504695b',
    messagingSenderId: '75887553218',
    projectId: 'th1-firebase',
    storageBucket: 'th1-firebase.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmmAJbx9EI2bE7vfIhHY1q82hjA3MVkY',
    appId: '1:75887553218:web:5c2e4d711e5e475804695b',
    messagingSenderId: '75887553218',
    projectId: 'th1-firebase',
    authDomain: 'th1-firebase.firebaseapp.com',
    storageBucket: 'th1-firebase.appspot.com',
  );
}
